# docker-compose.yaml
services:
  # 1. The Postgres Database
  database:
    image: postgres:16-alpine
    container_name: gategroup_db
    restart: unless-stopped
    env_file:
      - ./.env
    ports:
      - "5432:5432"
    volumes:
      - gategroup-db-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $POSTGRES_USER -d $POSTGRES_DB"]
      interval: 5s
      timeout: 5s
      retries: 5

  # 2. The Database Migrations
  migrations:
    image: flyway/flyway:10
    container_name: gategroup_migrations
    depends_on:
      database:
        condition: service_healthy
    env_file:
      - ./.env
    volumes:
      - ./database:/flyway/sql # Correct path
    command: "migrate"

  # 3. Your Backend API
  api:
    build:
      context: ./api # Correct path
      dockerfile: Dockerfile
    container_name: gategroup_api
    restart: unless-stopped
    depends_on:
      database:
        condition: service_healthy
    env_file:
      - ./.env
    ports:
      - "8080:8080" # Change if your API uses a different port
    volumes:
      - ./api:/app

  # 4. Your React Native App (Metro Bundler)
  app:
    build:
      context: ./trolley_app # Correct path
      dockerfile: Dockerfile
    container_name: gategroup_app
    restart: unless-stopped
    ports:
      - "8081:8081" # Metro
      - "19000-19002:19000-19002" # Expo
    volumes:
      - ./trolley_app:/app
      - /app/node_modules # Anonymous volume, same as your KNX setup

# Named volume for persistent DB data
volumes:
  gategroup-db-data: